name: CD

on:
  push:
    tags:
    - 'strata-source-*'

permissions:
  contents: write

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make -j$(nproc)
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: sar-linux
          path: sar.so
  build-win:
    name: Windows Build
    runs-on: windows-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: |
          msbuild SourceAutoRecord.sln /t:SourceAutoRecord /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false
          msbuild SourceAutoRecord.sln /t:proxy /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: sar-windows
          path: |
            bin/sar.dll
            bin/sar.pdb
            bin/scenefilecache.dll
            bin/scenefilecache.pdb
  release:
    name: Release  
    runs-on: ubuntu-latest
    needs: [build-lin, build-win]
    steps:
      - uses: actions/download-artifact@v4
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sar-linux.zip
            sar-windows.zip
