name: CD

on:
  push:
    tags:
    - 'strata-source-*'

permissions:
  contents: write

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make -j$(nproc)
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: sar-linux
          path: |
            sar.so
            sar.py
  build-win:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: |
          msbuild SourceAutoRecord.sln /t:SourceAutoRecord /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false
          msbuild SourceAutoRecord.sln /t:proxy /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: sar-windows
          path: |
            bin/sar.dll
            bin/sar.pdb
            bin/scenefilecache.dll
            bin/scenefilecache.pdb
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-lin, build-win]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create archives
        run: |
          7z a sar-windows.zip sar-windows/*
          7z a sar-linux.zip sar-linux/*
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: SAR for Strata Source
          body: |
            [Read README for installation](https://github.com/NeKzor/sar/blob/${{ github.ref_name }}/README.md)
            [Download for Windows](https://github.com/NeKzor/sar/releases/download/${{ github.ref_name }}/sar-windows.zip)
            [Download for Linux](https://github.com/NeKzor/sar/releases/download/${{ github.ref_name }}/sar-linux.zip)
          files: |
            sar-windows.zip
            sar-linux.zip
