name: CD

on:
  push:
    tags:
    - 'revolution-*'

permissions:
  contents: write

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: make get-deps
      - name: Build
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sar-linux
          path: sar.so
  build-win:
    name: Windows Build
    runs-on: windows-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SourceAutoRecord.sln /t:SourceAutoRecord /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SourceAutoRecord.sln /t:proxy /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sar-windows
          path: |
            bin/sar.dll
            bin/sar.pdb
            bin/audio_minimp3.dll
            bin/audio_minimp3.pdb
  release:
    name: Release  
    runs-on: ubuntu-latest
    needs: [build-lin, build-win]
    steps:
      - uses: actions/download-artifact@v4
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sar-linux.zip
            sar-windows.zip
