name: CI

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make
    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: sar-linux
        path: sar.so
  build-win:
    name: Windows Build
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SourceAutoRecord.sln /t:SourceAutoRecord /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SourceAutoRecord.sln /t:proxy /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: sar-windows
          path: |
            bin/sar.dll
            bin/sar.pdb
            bin/audio_minimp3.dll
            bin/audio_minimp3.pdb
